version: '3.8'

services:
  mitra-backend:
    build: .
    container_name: mitra-sanitaer-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./generated-pdfs:/app/generated-pdfs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mitra-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false
    tmpfs:
      - /tmp

  # Optional: Redis for rate limiting (if you want to scale)
  redis:
    image: redis:7-alpine
    container_name: mitra-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - mitra-network
    security_opt:
      - no-new-privileges:true

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: mitra-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/private:ro
    depends_on:
      - mitra-backend
    networks:
      - mitra-network
    security_opt:
      - no-new-privileges:true

networks:
  mitra-network:
    driver: bridge

volumes:
  redis-data:
    driver: local